#spring:
#  application:
#    name: zuul
#    
#server:
#  port: 3001
#  
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
#      
#zuul:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**      
#  retryable: true    
#  sensitive-headers:  
#  
#ribbon:
#  connectTimeout: 1000
#  ReadTimeout: 1000
#  MaxAutoRetries: 1
#  MaxAutoRetriesNextServer: 1
#  
#item-service:
#  ribbon:
#    MaxAutoRetries: 2
#    MaxAutoRetriesNextServer: 1
#    
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 500
#            
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
#
#turbine:
#  app-config: order-service,zuul
#  cluster-name-expression: new String("default")